# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

# controllers:
#     resource: routing.controllers

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    

connect_google:
    path: /connect/google
    controller: App\Controller\GoogleController::connect

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\GoogleController::connectCheck


# config/routes.yaml

# app_forgot_password:
#     path: /mot-de-passe-oublie
#     controller: App\Controller\ResetPasswordController::forgotPassword
#     methods: [GET, POST]

# app_reset_password:
#     path: /reinitialiser-mot-de-passe/{token}
#     controller: App\Controller\ResetPasswordController::resetPassword
#     methods: [GET, POST]    

mot_de_passe_oublie:
    path: /mot-de-passe-oublie
    controller: App\Controller\ResetPasswordController::request





