parameters:
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    openweather_api_key: '%env(OPENWEATHER_API_KEY)%'

services:

    Symfony\Contracts\HttpClient\HttpClientInterface: '@http_client'

    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\BadWordDetectorService:
        public: true
        arguments:
            $huggingfaceApiKey: '%env(string:HUGGINGFACE_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\WeatherService:
        arguments:
            $apiKey: '%openweather_api_key%'

    App\Service\HuggingFaceImageService:
        arguments:
            $client: '@http_client'

    App\Command\SendSmsAlertsCommand:
        arguments:
            $smsService: '@App\Service\SimpleSmsService'
        tags: ['console.command']

    App\Twig\NotificationExtension:
        arguments:
            $notifService: '@App\Service\NotificationService'
        tags:
            - { name: twig.extension }
